### ISSUE TITLE
Signature pad widget doesn't work

### ISSUE THREAD

**Issue by laulaz** [cguardia/questions#27]
* Questions version: 0.5.0a2
* Python version: 3.7.0
* Operating System: Mac OS 10.13.6

### Description

I try to use Signature pad widget from SurveyJS in my form.

### What I Did

Use this JSON:
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "signaturepad",
     "name": "question1",
     "title": "Signature"
    }
   ]
  }
 ]
}
```

The widget appears in the form but does nogthing : I can't use it as I can on SurveyJS "Test Survey".

**Comment by cguardia** [comment]
Turns out that there'a a bug in the SurveyJS signature pad widget. If the allow_clear property is set to false, the signature pad doesn't work at all. This happens on their own test survey page as well. We were setting the default value to False, which is not what SurveyJS does, so changed our default to True. That fixes the problem.
